# coding: utf-8
1 + 2
get_ipython().run_line_magic('pinfo', 'max')
get_ipython().system(' cd')
get_ipython().run_line_magic('cd', '')
get_ipython().run_line_magic('pwd', '')
get_ipython().run_line_magic('history', '')
get_ipython().run_line_magic('save', 'cmd.txt')
get_ipython().run_line_magic('save', "'cmd.txt'")
get_ipython().run_line_magic('save', 'cmd.txt 1-10')
get_ipython().run_line_magic('pwd', '')
get_ipython().system('dir')
get_ipython().system(' cd')
get_ipython().system(' dir')
get_ipython().run_line_magic('cd', 'e:\\classroom\\ds\\nov11')
get_ipython().system('pwd')
get_ipython().run_line_magic('pwd', '')
get_ipython().run_line_magic('save', 'cmd')
get_ipython().run_line_magic('save', 'cmd 1-20')
